## 경고! 이 파일은 업로드하지 마세요! 중요한 비밀키들이 저장되어 있어요. 로컬 개발환경에서만 사용하세요!
## WARNING! Do not upload this file! It contains important secret keys. Only use it in a local development environment!

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nest-lecture-dev:local
    ports:
      - '3002:3002'
      - '9229:9229'
    environment:
      NODE_ENV: development
      PORT: 3002
      CLOUDSQL_HOST: 34.64.248.193
      CLOUDSQL_USER: codelab
      CLOUDSQL_PASS: codelab1234
      CLOUDSQL_DB: codelab-nest
